### ISSUE TITLE
Issues with mod on server-side

### ISSUE THREAD

**Issue by gabriel-andreescu** [blay09/CraftingTweaks#129]
Hi, I've recently ran into a couple of problems when running CraftingTweaks on the server side.

1. in pair with the Crafting Station mod I'm getting a crash when I guess CT is trying to access/create client side config (log is below)
2. there's a weird behavior with shift clicking items, as soon as I removed CT from server side, the issue was gone. Basically if you split a stack of items in a container and you shift click them back into your inventory, you'll see that the items are not grouped into one stack but instead they cause a visual glitch until you reopen your inv. (note: mouse tweaks is causing a similar bug)

[12Oct2019 23:27:22.141] [modloading-worker-10/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2659/911685221@2cd169bd
java.lang.NullPointerException
	at net.blay09.mods.craftingtweaks.CraftingTweaksConfig.addModSupportOption(CraftingTweaksConfig.java:118)
	at net.blay09.mods.craftingtweaks.CraftingTweaksProviderManager.registerProvider(CraftingTweaksProviderManager.java:26)
	at net.blay09.mods.craftingtweaks.CraftingTweaks.lambda$processInterMod$1(CraftingTweaks.java:154)
	at net.minecraftforge.fml.InterModComms$QueueFilteringSpliterator.tryAdvance(InterModComms.java:171)
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at net.blay09.mods.craftingtweaks.CraftingTweaks.processInterMod(CraftingTweaks.java:55)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by BlayTheNinth** [comment]
Can't reproduce the second part with only Crafting Tweaks installed.

**Comment by gabriel-andreescu** [comment]
Thank you for the quick update, the second part was caused by secretrooms mod, but it was fixed by the author just now.
