### ISSUE TITLE
Server log error

### ISSUE THREAD

**Issue by sternschnaube** [blay09/CraftingTweaks#200]
### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.21

### Mod Version

18.0.1

### Balm Version

7.0.3

### Describe the Issue

I tried already to delete all configs, even Balm.
Nothing helped - the same occurs with Pretty Beaches and Gravelminer, either, all of these three mods are not working on my server.

Errors were encountered when loading the config file craftingtweaks-common.toml:
[22:09:16] [main/ERROR]: - Error loading config property [common] 'compressDenylist'
java.lang.NullPointerException: null
	at java.lang.Class.isAssignableFrom(Native Method) ~[?:?]
	at net.blay09.mods.balm.fabric.config.FabricConfigLoader.convertValue(FabricConfigLoader.java:212) ~[balm-fabric-1.20-7.0.3.jar:?]
	at net.blay09.mods.balm.fabric.config.FabricConfigLoader.convertValue(FabricConfigLoader.java:199) ~[balm-fabric-1.20-7.0.3.jar:?]
	at net.blay09.mods.balm.fabric.config.FabricConfigLoader.load(FabricConfigLoader.java:59) ~[balm-fabric-1.20-7.0.3.jar:?]
	at net.blay09.mods.balm.fabric.config.FabricBalmConfig.initializeBackingConfig(FabricBalmConfig.java:26) ~[balm-fabric-1.20-7.0.3.jar:?]
	at net.blay09.mods.balm.api.config.AbstractBalmConfig.registerConfig(AbstractBalmConfig.java:80) ~[balm-fabric-1.20-7.0.3.jar:?]
	at net.blay09.mods.craftingtweaks.config.CraftingTweaksConfig.initialize(CraftingTweaksConfig.java:13) ~[craftingtweaks-fabric-1.20-18.0.1.jar:?]
	at net.blay09.mods.craftingtweaks.CraftingTweaks.initialize(CraftingTweaks.java:21) ~[craftingtweaks-fabric-1.20-18.0.1.jar:?]
	at net.blay09.mods.balm.fabric.FabricBalmRuntime.initialize(FabricBalmRuntime.java:183) ~[balm-fabric-1.20-7.0.3.jar:?]
	at net.blay09.mods.balm.api.Balm.initialize(Balm.java:35) ~[balm-fabric-1.20-7.0.3.jar:?]
	at net.blay09.mods.craftingtweaks.FabricCraftingTweaks.onInitialize(FabricCraftingTweaks.java:9) ~[craftingtweaks-fabric-1.20-18.0.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[minecraft_server.jar:0.11.2]

**Comment by sternschnaube** [comment]
Thanks for the fast fix 🥳
