### ISSUE TITLE
Crash on start, latest release 1.20.6

### ISSUE THREAD

**Issue by sternschnaube** [blay09/CraftingTweaks#215]
### Minecraft Version

1.20.6

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Mod Version

Latest

### Balm Version

Latest

### Describe the Issue

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'craftingtweaks'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:484)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/blay09/mods/kuma/api/Kuma
	at net.blay09.mods.craftingtweaks.client.ModKeyMappings.initialize(ModKeyMappings.java:29)
	at net.blay09.mods.craftingtweaks.client.CraftingTweaksClient.initialize(CraftingTweaksClient.java:57)
	at net.blay09.mods.balm.fabric.client.FabricBalmClientRuntime.initialize(FabricBalmClientRuntime.java:65)
	at net.blay09.mods.balm.fabric.client.FabricBalmClientRuntime.initialize(FabricBalmClientRuntime.java:24)
	at net.blay09.mods.balm.api.client.BalmClient.initialize(BalmClient.java:15)
	at net.blay09.mods.craftingtweaks.fabric.client.FabricCraftingTweaksClient.onInitializeClient(FabricCraftingTweaksClient.java:13)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.blay09.mods.kuma.api.Kuma
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 13 more

**Comment by BlayTheNinth** [comment]
Crafting Tweaks requires the latest version of Balm to be installed.

**Comment by sternschnaube** [comment]
Having "balm-fabric-1.20.6-10.1.1" - or it's still not updated on Modrinth?
Server loads fine with this Balm version.

**Comment by BlayTheNinth** [comment]
Looks like the automated release failed. Balm 10.2.1 should be up now.

**Comment by sternschnaube** [comment]
Thanks.
